### PR TITLE
Tiny margin to bottom of HUD

### PR DESCRIPTION
**Pull request by nzkfc**
HUD icons were dead on edge of screen, didn't look quite right, needs a tiny bit of margin to break away from the screen edge, but not a lot to start overlapping on the map location.

### CODE REVIEW

**Comment by BerkieBb** [comment]
This change WILL overlap the hud on the minimap, you can change the 0.4 to 0.1 and it will be at the edge of the minimap so that is too close too, you can try to move the minimap a bit up to avoid this

**Comment by BerkieBb** [comment]
And I think 0.3 is a bit better than 0.4 as 0.4 is a tad bit too high I think

**Comment by BerkieBb** [comment]
image
I got it this high by putting the bottom to 0.3vw and reducing the Y of all the minimap components by 0.1

**Comment by nzkfc** [comment]
Yeah that looks much better! Noice!

**Comment by BerkieBb** [comment]
Can you get these changes in your pull request or shall I push it myself @nzkfc ?

**Comment by nzkfc** [comment]
> 
> 
> Can you get these changes in your pull request or shall I push it myself @nzkfc ?

Yeah i've updated mine now.... I think lol

**Comment by OfficialRDB** [comment]
> reducing the Y of all the minimap components by 0.1
Where can i find that ?

**Comment by OfficialRDB** [comment]
> 
> 
> image
> I got it this high by putting the bottom to 0.3vw and reducing the Y of all the minimap components by 0.1

Where can i find the minimap components ?

**Comment by OfficialRDB** [comment]
> 
> 
> image
> I got it this high by putting the bottom to 0.3vw and reducing the Y of all the minimap components by 0.1

Your preview looks great. 0.3 didnt work for me, even 0.1 is still to high + the can't get the map higher.

SetMinimapComponentPosition('minimap', 'L', 'B', -0.0045, -0.012, 0.150, 0.188888)
SetMinimapComponentPosition('minimap_mask', 'L', 'B', 0.020, 0.022, 0.111, 0.159)
SetMinimapComponentPosition('minimap_blur', 'L', 'B', -0.03, 0.012, 0.266, 0.237)

**Pull request closed without merging**
