### PR TITLE
add oxygen and engine stats

### PR DESCRIPTION
**Pull request by haitham1337**

### CODE REVIEW

**Comment by Dankbudbaker** [comment]
I get a 404 error when trying to look at these changes

**Comment by haitham1337** [comment]
@Dankbudbaker github broken site

**Comment by Dankbudbaker** [comment]
ahh I see

**Comment by zfbx** [comment]
This is just the lua side.. there's no html elements that hook to these?

**Comment by haitham1337** [comment]
github Had problems It seems that the suggestion was not stored after submitting the suggestion I will send it again today

**Comment by tonyydung126** [comment]
hello, Evanillaa, do you have any update about oxygen ?

**Comment by haitham1337** [comment]
not complete wait

**Comment by tonyydung126** [comment]
> not complete wait

Okay, i will wait . Many thanks to you

**Comment by Dankbudbaker** [comment]
so are we still waiting ?

**Comment by Rhydium** [comment]
Hey @evanillaa! Any updates on this?

**Pull request closed without merging**
