### PR TITLE
Stress Effect

### PR DESCRIPTION
**Pull request by ghost**
**Describe Pull request**
Improve the stress effect from shake and flash to blur the screen

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

### CODE REVIEW

**Comment by loljoshie** [comment]
> **Describe Pull request** Improve the stress effect from shake and flash to blur the screen
> 
> **Questions (please complete the following information):**
> 
> * Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
> * Does your code fit the style guidelines? yes
> * Does your PR fit the contribution guidelines? yes

If you could change that PR to match with the newest client update I'll happily merge! (I don't want to steal your PR) thanks!

**Comment by ghost** [comment]
Ok i will update it in the morning

**Comment by ghost** [comment]
> > **Describe Pull request** Improve the stress effect from shake and flash to blur the screen
> > **Questions (please complete the following information):**
> > 
> > * Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
> > * Does your code fit the style guidelines? yes
> > * Does your PR fit the contribution guidelines? yes
> 
> If you could change that PR to match with the newest client update I'll happily merge! (I don't want to steal your PR) thanks!

already updated

**Comment by ghost** [comment]
And i had made Interaction system build in it if u want i can share it

**Comment by darknight2590** [comment]
conflicts

**Comment by loljoshie** [comment]
Still conflicts, it may be best to just reopen a new PR!

**Comment by ghost** [comment]
Ok

**Pull request closed without merging**
