### PR TITLE
FPS Boost add to Menu

### PR DESCRIPTION
**Pull request by AnishBplayz**
This is a pull request, that adds a FPS Boost Option to the Hud Menu (/menu)

image
image

### CODE REVIEW

**Review by Kingsage311 — CHANGES_REQUESTED** [review]
Please fix the lint and explain how this "boosts fps"

**Comment by AnishBplayz** [comment]
Basically this script gives an Fps Boost Ingame when enabled. 

The timecycle modifier set to that script disables shadows and cloud effects a bit which gives people with low end specs atleast a buff of 10-15 fps.

Maybe for mid end pc and high end pc it wont affect anything to fps but have tested with people using just low end laptops and pc which gave them a buff so thought to PR it for the community.

**Comment by AnishBplayz** [comment]
Also I am new to the lint thing so can you guide me how to fix it ?

**Comment by JericoFX** [comment]
Hi, nice addition, check here https://prnt.sc/yG5Zr1x0eXzs will tell you the lint issues

**Comment by AnishBplayz** [comment]
image

These things aren't the issue i suppose..

**Pull request closed without merging**
