### PR TITLE
Update client.lua

### LINKED ISSUE #140: [BUG] My engine status don't go away when im off the vehicle
When i am off the vehicle, the engine health icon dosen't go away

image

### PR DESCRIPTION
**Pull request by zWyzzzzz**
fix https://github.com/qbcore-framework/qb-hud/issues/140

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by milotiro95** [comment]
More like this line 23
`local engine = -1`

**Comment by zWyzzzzz** [comment]
> More like this line 23 `local engine = -1`

its work for you?

**Comment by Andyauk** [comment]
> > More like this line 23 `local engine = -1`
> 
> its work for you?

worked for me . there suggestion. your also works.

**Comment by milotiro95** [comment]
Yes it works also

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-hud/commit/31fabf50d51bf521ca160d15d7525110a57837c2

**Pull request closed without merging**
