### PR TITLE
Add stamina bar

### PR DESCRIPTION
**Pull request by gimbald**
As per suggestion #21 add bars for stamina and oxygen.

oxygen-stamina

Tested on build with latest changes.

### CODE REVIEW

**Comment by Dankbudbaker** [comment]
i've notice that sometimes oxygen and stamina wont show up with these changes. any idea?

**Comment by gimbald** [comment]
They only show up if they are being used, if your stamina or oxygen is full they don't show up to avoid cluttering your screen at the bottom.

**Comment by Dankbudbaker** [comment]
for me they work once, they show correctly then when they fill up again they don't show back up?

**Review by haitham1337 — APPROVED** [review]

**Comment by haitham1337** [comment]
@GhzGarage Useful addition
I don't know why it was not approved

**Comment by trinhmanhcuong** [comment]
How to detect oxygen when using diving gear?

**Comment by BerkieBb** [comment]
This pull request has conflicts now

**Comment by Demo4889** [comment]
Stamina and Oxygen were added with #64

**Pull request closed without merging**
