### PR TITLE
Fix linting issues

### PR DESCRIPTION
**Pull request by D4isDAVID**
**Describe Pull request**
Fix linter issues introduced by 31fabf5 and #145

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **no**
- Does your code fit the style guidelines? **yes**
- Does your PR fit the contribution guidelines? **yes**

### CODE REVIEW

**Review by mrdiamonddirt — APPROVED** [review]
looks good 😊

**Comment by tom-osborne** [comment]
@D4isDAVID not sure why the linter is confused, but `engine` is used in a few places. Have you checked this doesn't cause any issues?

**Comment by D4isDAVID** [comment]
> @D4isDAVID not sure why the linter is confused, but `engine` is used in a few places. Have you checked this doesn't cause any issues?

Actually it doesn't seem to be used. In [line 547](https://github.com/qbcore-framework/qb-hud/blob/main/client.lua#L547) it gets assigned a value, and although the *word* engine comes up in a few places like other variables and a table, in the table it shows up as a key and not a value ([line 653](https://github.com/qbcore-framework/qb-hud/blob/main/client.lua#L653)). The *variable* itself doesn't seem to be used anywhere.

**Comment by D4isDAVID** [comment]
Actually I should remove that variable assignment as well...

**Pull request closed without merging**
